artifacts_root: artifacts

# dictionary format of yaml file
data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/data.csv
  local_train_file: artifacts/data_ingestion/train.csv
  local_val_file: artifacts/data_ingestion/validation.csv
  local_test_file: artifacts/data_ingestion/test.csv

data_transformation:
  root_dir: artifacts/transformation
  local_train_dir: artifacts/transformation/train
  local_val_dir: artifacts/transformation/validation
  local_test_dir: artifacts/transformation/test
  local_target_file: artifacts/transformation/target_variables.pkl
  local_preprocessor_file: artifacts/transformation/preprocessor.pkl

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  model_path: artifacts/prepare_base_model/base_model.h5
  updated_model_path: artifacts/prepare_base_model/base_model_updated.h5

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  ckeckpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5

