artifacts_root: artifacts

# dictionary format of yaml file
data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/data.csv
  local_train_file: artifacts/data_ingestion/train.csv
  local_val_file: artifacts/data_ingestion/validation.csv
  local_test_file: artifacts/data_ingestion/test.csv

data_transformation:
  root_dir: artifacts/data_transformation
  
  local_train_angry_dir: artifacts/data_transformation/train/angry
  local_train_disgust_dir: artifacts/data_transformation/train/disgust
  local_train_fear_dir: artifacts/data_transformation/train/fear
  local_train_happy_dir: artifacts/data_transformation/train/happy
  local_train_sad_dir: artifacts/data_transformation/train/sad
  local_train_surprise_dir: artifacts/data_transformation/train/surprise
  local_train_nuetral_dir: artifacts/data_transformation/train/nuetral

  local_val_angry_dir: artifacts/data_transformation/validation/angry
  local_val_disgust_dir: artifacts/data_transformation/validation/disgust
  local_val_fear_dir: artifacts/data_transformation/validation/fear
  local_val_happy_dir: artifacts/data_transformation/validation/happy
  local_val_sad_dir: artifacts/data_transformation/validation/sad
  local_val_surprise_dir: artifacts/data_transformation/validation/surprise
  local_val_nuetral_dir: artifacts/data_transformation/validation/nuetral

  local_test_angry_dir: artifacts/data_transformation/test/angry
  local_test_disgust_dir: artifacts/data_transformation/test/disgust
  local_test_fear_dir: artifacts/data_transformation/test/fear
  local_test_happy_dir: artifacts/data_transformation/test/happy
  local_test_sad_dir: artifacts/data_transformation/test/sad
  local_test_surprise_dir: artifacts/data_transformation/test/surprise
  local_test_nuetral_dir: artifacts/data_transformation/test/nuetral
  

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  model_path: artifacts/prepare_base_model/base_model.h5
  updated_model_path: artifacts/prepare_base_model/base_model_updated.h5
  updated_model_json_path: artifacts/prepare_base_model/base_model_updated.json

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  ckeckpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  trained_model_json_path: artifacts/training/model.json

